[project]
name = "L3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "James Clause", email = "clause@udel.edu" }]
requires-python = ">=3.14"
dependencies = ["click>=8.3.1", "pydantic>=2.12.3", "util"]


[tool.uv]
package = true

[project.scripts]
L3 = "L3:main.main"
